version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5173:5173
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes: 
      - ./frontend:/app-frontend
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend:/app-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/lexartdb
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      # Os dados abaixo se referem ao container `lexartDB`
      - DB_PORT=27017

  mongodb:
    image: mongo:5.0.7
    container_name: lexart_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./:/app